app = 'simple-icons-cdn'
primary_region = 'sjc'

[build]

[env]
  PORT = '8000'

[processes]
  app = 'task serve'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 3
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
