app = 'simple-icons-cdn'
primary_region = 'hkg'

[build]

[env]
  PORT = '8080'

[processes]
  app = 'run --allow-net ./source/app.js'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 3
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
