name: Deno
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Deno
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: deno fmt --check
      - run: deno lint
      - run: deno test
